# Generated by Django 4.0.1 on 2022-01-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('courseNumber', models.IntegerField()),
                ('instructorName', models.CharField(max_length=60)),
                ('duration', models.FloatField()),
            ],
        ),
    ]
